// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"sx-go/internal/repository"
	"sx-go/internal/repository/dao"
	"sx-go/internal/service"
	"sx-go/internal/web"
	"sx-go/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	client := ioc.InitMongodb()
	v := ioc.InitMiddlewares(client)
	userDaoInterface := dao.NewUserDao(client)
	userRepoInterface := repository.NewUserRepo(userDaoInterface)
	userServiceInterface := service.NewUserService(userRepoInterface)
	userHandler := web.NewUserHandler(userServiceInterface)
	engine := ioc.InitGin(v, userHandler)
	app := &App{
		server:  engine,
		DB: client,
	}
	return app
}
